### ISSUE TITLE
Error loading acorn

### ISSUE THREAD

**Issue by ForbesLindesay** [petehunt/node-jsx#46]
The following code:

```js
require('node-jsx').install();
var acorn = require('acorn');
```

Results in:

```
/Users/forbeslindesay/Documents/GitHub/temp/node_modules/acorn/dist/acorn.js:2981
  _classCallCheck(this, TokContext);
                        ^
ReferenceError: TokContext is not defined
    at new TokContext (/Users/forbeslindesay/Documents/GitHub/temp/node_modules/acorn/dist/acorn.js:2981:25)
    at Object.15../state (/Users/forbeslindesay/Documents/GitHub/temp/node_modules/acorn/dist/acorn.js:2990:11)
    at s (/Users/forbeslindesay/Documents/GitHub/temp/node_modules/acorn/dist/acorn.js:1:681)
    at /Users/forbeslindesay/Documents/GitHub/temp/node_modules/acorn/dist/acorn.js:1:732
    at Object.1../expression (/Users/forbeslindesay/Documents/GitHub/temp/node_modules/acorn/dist/acorn.js:78:21)
    at s (/Users/forbeslindesay/Documents/GitHub/temp/node_modules/acorn/dist/acorn.js:1:681)
    at e (/Users/forbeslindesay/Documents/GitHub/temp/node_modules/acorn/dist/acorn.js:1:852)
    at /Users/forbeslindesay/Documents/GitHub/temp/node_modules/acorn/dist/acorn.js:1:870
    at a (/Users/forbeslindesay/Documents/GitHub/temp/node_modules/acorn/dist/acorn.js:1:150)
    at Object.<anonymous> (/Users/forbeslindesay/Documents/GitHub/temp/node_modules/acorn/dist/acorn.js:1:383)
```

but

```js
var acorn = require('acorn');
```

works fine.

See jadejs/jade#1925

**Comment by JMLX42** [comment]
+1 I have the same error.

```
vagrant/www/node_modules/keystone/node_modules/jade/node_modules/constantinople/node_modules/acorn/dist/acorn.js:2275
  _classCallCheck(this, TokContext);
                        ^
ReferenceError: TokContext is not defined
    at new TokContext (/vagrant/www/node_modules/keystone/node_modules/jade/node_modules/constantinople/node_modules/acorn/dist/acorn.js:2275:25)
    at Object../state (/vagrant/www/node_modules/keystone/node_modules/jade/node_modules/constantinople/node_modules/acorn/dist/acorn.js:2285:11)
    at s (/vagrant/www/node_modules/keystone/node_modules/jade/node_modules/constantinople/node_modules/acorn/dist/acorn.js:1:681)
    at /vagrant/www/node_modules/keystone/node_modules/jade/node_modules/constantinople/node_modules/acorn/dist/acorn.js:1:732
    at Object../expression (/vagrant/www/node_modules/keystone/node_modules/jade/node_modules/constantinople/node_modules/acorn/dist/acorn.js:907:21)
    at s (/vagrant/www/node_modules/keystone/node_modules/jade/node_modules/constantinople/node_modules/acorn/dist/acorn.js:1:681)
    at e (/vagrant/www/node_modules/keystone/node_modules/jade/node_modules/constantinople/node_modules/acorn/dist/acorn.js:1:852)
    at /vagrant/www/node_modules/keystone/node_modules/jade/node_modules/constantinople/node_modules/acorn/dist/acorn.js:1:870
    at a (/vagrant/www/node_modules/keystone/node_modules/jade/node_modules/constantinople/node_modules/acorn/dist/acorn.js:1:150)
    at Object.<anonymous> (/vagrant/www/node_modules/keystone/node_modules/jade/node_modules/constantinople/node_modules/acorn/dist/acorn.js:1:383)
    at Module._compile (module.js:460:26)
    at Object.require.extensions.(anonymous function) [as .js] (/vagrant/www/node_modules/node-jsx/index.js:29:12)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```
